---
# This playbook deploys a new EC2 instance

- hosts: localhost
  connection: local
  gather_facts: False
  vars_prompt:
    - name: vpc_id
      prompt: "VPC id"
      private: no
      default: vpc-d8c0f4bc
    - name: subnet_id
      prompt: "Subnet id"
      private: no
      default: subnet-b68a16c0
  tasks:
    - name: Create EC2 Security Group
      ec2_group:
        name: ghuser-sg
        description: ghuser
        region: us-east-1
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    - name: Create EC2 instance
      ec2:
        key_name: ghuser
        region: us-east-1
        vpc_subnet_id: "{{ subnet_id }}"
        group: "default,ghuser-sg"
        image: ami-759bc50a # Ubuntu 16.04 hvm:ebs-ssd
        instance_type: t2.nano
        wait: true
        instance_tags:
          Name: "ghuser"
      register: created_instance
    - add_host:
        hostname: "{{ created_instance.instances[0].public_ip }}"
        groupname: created_instance

# FIXME: doesn't work, immediately fails with
# TASK [Wait for SSH to come up] *******************************************************************
# fatal: [54.205.1.207]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host
# via ssh: ssh: connect to host 54.205.1.207 port 22: Connection refused\r\n", "unreachable": true}
- hosts: created_instance
  gather_facts: False
  user: ubuntu
  tasks:
    - name: Wait for SSH to come up
      wait_for:
        port: 22

- hosts: created_instance
  gather_facts: True
  user: ubuntu
  tasks:
    - debug:
        msg: |
          EC2 instance ready. You can e.g. do:
          $ ssh -i secret.pem ubuntu@{{ ec2_ip_address }}
          $ tmux new-session -s 0
          [C-b d]
          $ tmux attach -t 0
          $ cd ghuser.io/db/
          $ npm install
          $ export GITHUB_CLIENT_ID=0123456789abcdef0123
          $ export GITHUB_CLIENT_SECRET=0123456789abcdef0123456789abcdef01234567
          $ export GITHUB_USERNAME=AurelienLourot
          $ export GITHUB_PASSWORD=********
          $ ./fetch.js

# TODO:
# curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
# sudo apt-get install -y nodejs
# git clone https://AurelienLourot@github.com/AurelienLourot/ghuser.io.git
# terminate instance (volume gets removed automatically)
