---

# Note: we chose riofs over s3fs because:
# * s3fs is very slow for us because we have thousands of small files,
#   see https://serverfault.com/questions/396100/s3fs-performance-improvements-or-alternative
# * s3fs spuriously gets stuck, see https://github.com/s3fs-fuse/s3fs-fuse/issues/441

- name: Install riofs' deps
  apt:
    name: "{{ item }}"
  become: True
  with_items:
    - build-essential
    - gcc
    - make
    - automake
    - autoconf
    - libtool
    - pkg-config
    - intltool
    - libglib2.0-dev
    - libfuse-dev
    - libxml2-dev
    - libevent-dev
    - libssl-dev

- name: Download riofs
  unarchive:
    remote_src: yes
    src: https://github.com/skoobe/riofs/archive/v0.6.tar.gz
    dest: /tmp/

- name: Build riofs
  shell: ./autogen.sh && ./configure && make
  args:
    chdir: /tmp/riofs-0.6

- name: Install riofs
  shell: make install
  args:
    chdir: /tmp/riofs-0.6
  become: True

- name: Create ~/s3/
  file:
    path: /home/ubuntu/s3
    state: directory
    mode: 0700

- name: Mount the S3 bucket
  shell: bash -c "source /home/ubuntu/.bash_profile && riofs ghuser /home/ubuntu/s3"
